### ISSUE TITLE
doesn't get the scope right

### ISSUE THREAD

**Issue by Maxhodges** [windwp/vscode-expand-region#10]
I started at `Last Order` but it doesn't expand the scope right. it's including closing divs but not their counterpart (open divs)

![image](https://user-images.githubusercontent.com/957271/29002812-ef5eae46-7ae5-11e7-8e7e-ede913aeefe6.png)

**Comment by Maxhodges** [comment]
expected (ala webstorm) 
![exzto](https://user-images.githubusercontent.com/957271/29002860-f18f1c90-7ae6-11e7-86f8-7e656be036d7.gif)

**Comment by Jasonlhy** [comment]
I also faced the same problem.
