### ISSUE TITLE
Overrides ⌘-w not ⌃-w

### ISSUE THREAD

**Issue by yankeeinlondon** [windwp/vscode-expand-region#2]
On the mac this overrides ⌘-w which is a big no-no. I think this should have been CTRL-w as the documentation states.

**Comment by windwp** [comment]
you can change it by set keyboard shortcut

"key": "ctrl+w","command": "expand_region"

**Comment by yankeeinlondon** [comment]
Well actually the problem is worse than this. Setting it to a new value of whatever you want is easy enough. The problem is that the default behaviour of the addon is to clobber one of the most common keyboard shortcuts that people use.  To recover people must manually override the override:

"key": "cmd+w","command": "workbench.action.closeActiveEditor"

this works but is rather unsatisfying since now my "default keyboard shortcuts" define ⌘w twice and I come in at the end and set it a third time.

**Comment by windwp** [comment]
I just disable default keybinding. You can upgrade extension right now.

**Comment by yankeeinlondon** [comment]
ok thanks
