### ISSUE TITLE
Feature request: handle multiple selections

### ISSUE THREAD

**Issue by bgoscinski** [windwp/vscode-expand-region#6]
Just like sublime version.

Sublime: 
![sublime-expand-region](https://cloud.githubusercontent.com/assets/5730169/22105779/eff8fad8-de45-11e6-8382-db4b3bb6a4d5.gif)

VS Code:
![vscode-expand-region](https://cloud.githubusercontent.com/assets/5730169/22105787/fd875a14-de45-11e6-9dc2-8a589418cdbb.gif)

**Comment by nicooprat** [comment]
This alternative works with multiple cursors but don't have the undo-expand feature... https://marketplace.visualstudio.com/items?itemName=vittorioromeo.expand-selection-to-scope
