### ISSUE TITLE
Should expand to within brackets/tags THEN to parent tag/bracket

### ISSUE THREAD

**Issue by Noitidart** [windwp/vscode-expand-region#9]
Hi there,

Many many times I need to expand the region to be just the lines between the brackets  (or html/jsx tags). As seen in this video on youtube I uploaded here:

https://youtu.be/OVi47bLyYHQ

You see I was trying to select just the 3 rows, init/add/edit because i wanted to tab them.

Also seen in your readme gif:

![](https://raw.githubusercontent.com/windwp/vscode-expand-region/master/image/html.gif)

Expanding should first give me an option of just all the `<li>` tags so I can indent them.

May you please hook this up sir. I really love this extension!

**Comment by windwp** [comment]
I know your issue but it expands same selection like sublime and webstorm.

**Comment by Noitidart** [comment]
Is it possible to get an option please? Or if you can show me how to edit it please? Excuse the persistence please it's just I really need it and can't anything else as good as your extension :)
